### ISSUE TITLE
ACF Fields not saving

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#25] opened 2016-07-01 15:45 UTC
ACF fields in property not saving.

I think this has cropped up before, but an update fixed it.

Seems to have arisen again with latest update.

Thanks,
Tom

**Comment by propertyhive** [comment] 2016-07-04 08:42
Hmm.. Yeh we had this arise ages ago. The cause was the $post variable getting overwritten somewhere in one of the meta boxes.

I'll get ACF setup shortly and see if I can recreate this. Keep you posted.

**Comment by propertyhive** [comment] 2016-07-13 16:49
This should be fixed in version 1.1.6

**Closed by propertyhive** 2016-07-13 16:49 UTC
Labels: bug
