### ISSUE TITLE
Property Hive-Only Mode on the new Wordpress 5.9.1 causing critical error

### ISSUE THREAD

**Issue by mikemhb** [propertyhive/WP-Property-Hive#182] opened 2022-02-27 22:37 UTC
Property Hive-Only Mode on the new Wordpress 5.9.1 causing critical error

**Comment by propertyhive** [comment] 2022-02-28 17:08
Thanks for reporting this. I can see the same thing was raised on our Facebook where we replied saying we hadn't been able to recreate it and requested more details/WP login/errors. Please let me know if more info can be provided and we'll look into this accordingly.

Thanks,
Steve

**Comment by mikemhb** [comment] 2022-02-28 22:31
Hi Steve,

Thanks for getting back to me.

I have created you 2 users so that you can test this out.

https://tiptreehomes.co.uk/wp-admin

steve
steve2

passwords are the same, both: Mr)QO2iEupq!oB9WWMg8e3U9

If you login with both you will see they both work fine. Then if you use
steve to set steve2 to "property hive only mode" and refresh, you will see
that you get a critical error.

Please let me know if there is anything else you need.

Thanks

Mike
IMPROVE MEDIA [image: Logo] <https://improvemedia.co.uk/>

Tiptree, Essex
t: +44 01621 810561
e: ***@***.***

improvemedia.co.uk <https://fb.me/improvemedia.uk>
<https://www.instagram.com/improvemedia_uk/>
<https://twitter.com/Improvemedia_uk>
<https://www.linkedin.com/company/improve-media-essex>
<http://google.co.uk/search?q=Improve+Media&ludocid=16396880959785690814&lsig=AB86z5VIReOmSpjjVg4H6keEItpi#fpstate=lie&lrd=0x47d8e357d347d087:0xe38d6c5bc86466be,3,,,>
  <https://wa.me/447444731972>

[image: Banner] <https://improvemedia.co.uk/>

The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.

**Comment by mikemhb** [comment] 2022-02-28 22:33
When the error occurs we get sent the below error report.




---------- Forwarded message ---------
From: WordPress ***@***.***>
Date: Mon, 28 Feb 2022 at 22:26
Subject: [Tiptree Homes Estate Agents] Your Site is Experiencing a
Technical Issue
To: ***@***.***>


Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin
or theme causes a fatal error on your site, and notifies you with this
automated email.

In this case, WordPress caught an error with one of your plugins, Property
Hive.

First, visit your website (https://tiptreehomes.co.uk/) and check for any
visible issues. Next, visit the page where the error was caught (
https://tiptreehomes.co.uk/wp-admin/edit.php?s&post_status=all&post_type=property&action=-1&_department&_marketing&_availability_id=4&_location_id&_office_id&_negotiator_id=0&seo_filter&readability_filter&filter_action=Filter&paged=1&action2=-1)
and check for any visible issues.

Please contact your host for assistance with investigating this issue
further.

If your site appears broken and you can't access your dashboard normally,
WordPress now has a special "recovery mode". This lets you safely login to
your dashboard and investigate further.

https://tiptreehomes.co.uk/wp-login.php?action=enter_recovery_mode&rm_token=cdlecKmnYLmfLIBU8Lnd1p&rm_key=fIWXQWFxCpq2YyIBCqv4De

To keep your site safe, this link will expire in 1 day. Don't worry about
that, though: a new link will be emailed to you if the error occurs again
after it expires.

When seeking help with this issue, you may be asked for some of the
following information:
WordPress version 5.9.1
Current theme: Astra (version 3.7.7)
Current plugin: Property Hive (version 1.5.31)
PHP version 7.3.33



Error Details
=============
An error of type E_ERROR was caused in line 108 of the file /home/mikeb892/
tiptreehomes.co.uk/wp-content/plugins/propertyhive/includes/admin/class-ph-admin-menus.php.
Error message: Uncaught Error: Call to undefined function PHC() in
/home/mikeb892/
tiptreehomes.co.uk/wp-content/plugins/propertyhive/includes/admin/class-ph-admin-menus.php:108
Stack trace:
#0 /home/mikeb892/tiptreehomes.co.uk/wp-includes/class-wp-hook.php(307):
PH_Admin_Menus->crm_only_mode_menu('')
#1 /home/mikeb892/tiptreehomes.co.uk/wp-includes/class-wp-hook.php(331):
WP_Hook->apply_filters(NULL, Array)
#2 /home/mikeb892/tiptreehomes.co.uk/wp-includes/plugin.php(474):
WP_Hook->do_action(Array)
#3 /home/mikeb892/tiptreehomes.co.uk/wp-admin/includes/menu.php(155):
do_action('admin_menu', '')
#4 /home/mikeb892/tiptreehomes.co.uk/wp-admin/menu.php(394):
require_once('/home/mikeb892/...')
#5 /home/mikeb892/tiptreehomes.co.uk/wp-admin/admin.php(158):
require('/home/mikeb892/...')
#6 /home/mikeb892/tiptreehomes.co.uk/wp-admin/edit.php(10):
require_once('/home/mikeb892/...')
#7 {main}
  thrown

**Comment by propertyhive** [comment] 2022-03-01 11:49
Thanks for the details. The issue is to do with the Calendar add on and was was fixed in version 1.0.19. You're running version 1.0.16. I'm attaching below the latest version 1.0.22 for you:

https://we.tl/t-XPBhAnQWhV

Thanks
Steve

**Closed by propertyhive** 2022-03-01 11:49 UTC

**Comment by mikemhb** [comment] 2022-03-01 11:56
Fantastic!! Thank you

Mike
IMPROVE MEDIA [image: Logo] <https://improvemedia.co.uk/>

Tiptree, Essex
t: +44 01621 810561
e: ***@***.***

improvemedia.co.uk <https://fb.me/improvemedia.uk>
<https://www.instagram.com/improvemedia_uk/>
<https://twitter.com/Improvemedia_uk>
<https://www.linkedin.com/company/improve-media-essex>
<http://google.co.uk/search?q=Improve+Media&ludocid=16396880959785690814&lsig=AB86z5VIReOmSpjjVg4H6keEItpi#fpstate=lie&lrd=0x47d8e357d347d087:0xe38d6c5bc86466be,3,,,>
  <https://wa.me/447444731972>

[image: Banner] <https://improvemedia.co.uk/>

The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.
